# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
[versions]
fabric8 = "7.5.2"
lombok = "1.18.42"
netty = "4.2.10.Final"
operator-sdk = "5.2.3"
dropwizard-metrics = "4.2.37"
spark = "4.1.1"
hadoop = "3.4.3"
log4j = "2.24.3"
slf4j = "2.0.17"

# Test
junit = "6.0.0"
jacoco = "0.8.14"
mockito = "5.21.0"

# Build Analysis
checkstyle = "13.0.0"
pmd = "7.21.0"
spotbugs-tool = "4.9.8"
spotbugs-plugin = "6.4.7"
spotless-plugin = "8.1.0"

# Packaging
cyclonedx = "2.4.1"
shadow-jar-plugin = "8.3.9"

[libraries]
kubernetes-client = { group = "io.fabric8", name = "kubernetes-client", version.ref = "fabric8" }
kubernetes-httpclient-vertx = { group = "io.fabric8", name = "kubernetes-httpclient-vertx", version.ref = "fabric8" }
kubernetes-server-mock = { group = "io.fabric8", name = "kubernetes-server-mock", version.ref = "fabric8" }
kube-api-test-client-inject = {group = "io.fabric8", name = "kube-api-test-client-inject", version.ref = "fabric8"}
crd-generator-apt = { group = "io.fabric8", name = "crd-generator-apt", version.ref = "fabric8" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
log4j-layout-template-json = { group = "org.apache.logging.log4j", name = "log4j-layout-template-json", version.ref = "log4j" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
operator-framework = { group = "io.javaoperatorsdk", name = "operator-framework", version.ref = "operator-sdk"}
operator-framework-junit5 = { group = "io.javaoperatorsdk", name = "operator-framework-junit-5", version.ref = "operator-sdk"}
spotbugs-annotations = { group = "com.github.spotbugs", name = "spotbugs-annotations", version.ref = "spotbugs-tool"}
metrics-core = { group = "io.dropwizard.metrics", name = "metrics-core", version.ref = "dropwizard-metrics"}
metrics-jvm = { group = "io.dropwizard.metrics", name = "metrics-jvm", version.ref = "dropwizard-metrics"}
spark-core = { group = "org.apache.spark", name = "spark-core_2.13", version.ref = "spark"}
spark-kubernetes = { group = "org.apache.spark", name = "spark-kubernetes_2.13", version.ref = "spark"}
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito"}
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit"}
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit"}
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher"}
spotbugs-gradle-plugin = { group = "com.github.spotbugs.snom", name = "spotbugs-gradle-plugin", version.ref = "spotbugs-plugin" }
spotless-plugin-gradle = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless-plugin" }
shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow-jar-plugin"}
cyclonedx-bom = { group = "org.cyclonedx.bom", name = "org.cyclonedx.bom.gradle.plugin", version.ref = "cyclonedx" }
